package arc.input

/**
 * All keys in controller, keyboard and mouse.
 */
enum class KeyCode(
    val keyType: KeyType,
    val value: Char? = null,
    val axis: Boolean = false
) {

    //controller
    CONTROLLER_A(KeyType.CONTROLLER),
    CONTROLLER_B(KeyType.CONTROLLER),
    CONTROLLER_X(KeyType.CONTROLLER),
    CONTROLLER_Y(KeyType.CONTROLLER),
    CONTROLLER_GUIDE(KeyType.CONTROLLER),
    CONTROLLER_L_BUMPER(KeyType.CONTROLLER),
    CONTROLLER_R_BUMPER(KeyType.CONTROLLER),
    CONTROLLER_BACK(KeyType.CONTROLLER),
    CONTROLLER_START(KeyType.CONTROLLER),
    CONTROLLER_L_STICK(KeyType.CONTROLLER),
    CONTROLLER_R_STICK(KeyType.CONTROLLER),

    //pov
    CONTROLLER_PAD_UP(KeyType.CONTROLLER),
    CONTROLLER_PAD_DOWN(KeyType.CONTROLLER),
    CONTROLLER_PAD_LEFT(KeyType.CONTROLLER),
    CONTROLLER_PAD_RIGHT(KeyType.CONTROLLER),

    //controller axes
    CONTROLLER_L_TRIGGER(KeyType.CONTROLLER, axis = true),
    CONTROLLER_R_TRIGGER(KeyType.CONTROLLER, axis = true),
    CONTROLLER_L_STICK_Y_AXIS(KeyType.CONTROLLER, axis = true),
    CONTROLLER_L_STICK_X_AXIS(KeyType.CONTROLLER, axis = true),
    CONTROLLER_R_STICK_Y_AXIS(KeyType.CONTROLLER, axis = true),
    CONTROLLER_R_STICK_X_AXIS(KeyType.CONTROLLER, axis = true),

    //mouse
    MOUSE_LEFT(KeyType.MOUSE),
    MOUSE_RIGHT(KeyType.MOUSE),
    MOUSE_MIDDLE(KeyType.MOUSE),
    MOUSE_BACK(KeyType.MOUSE),
    MOUSE_FORWARD(KeyType.MOUSE),

    //scroll
    MOUSE_SCROLL(KeyType.SCROLL, axis = true),

    //keyboard
    KEY_ESCAPE(KeyType.KEY),
    KEY_LMETA(KeyType.KEY),
    KEY_RMETA(KeyType.KEY),
    KEY_LCONTROL(KeyType.KEY),
    KEY_RCONTROL(KeyType.KEY),
    KEY_LSHIFT(KeyType.KEY),
    KEY_RSHIFT(KeyType.KEY),
    KEY_LMENU(KeyType.KEY),
    KEY_RMENU(KeyType.KEY),
    KEY_MENU(KeyType.KEY),
    KEY_MINUS(KeyType.KEY, '-'),
    KEY_EQUALS(KeyType.KEY, '='),
    KEY_BACKSPACE(KeyType.KEY),
    KEY_ENTER(KeyType.KEY),
    KEY_TAB(KeyType.KEY),
    KEY_LBRACKET(KeyType.KEY, '['),
    KEY_RBRACKET(KeyType.KEY, ']'),
    KEY_SEMICOLON(KeyType.KEY, ';'),
    KEY_APOSTROPHE(KeyType.KEY, '\''),
    KEY_GRAVE(KeyType.KEY, '`'),
    KEY_BACKSLASH(KeyType.KEY, '\\'),
    KEY_COMMA(KeyType.KEY, ','),
    KEY_PERIOD(KeyType.KEY, '.'),
    KEY_SLASH(KeyType.KEY, '/'),
    KEY_MULTIPLY(KeyType.KEY, '*'),
    KEY_SPACE(KeyType.KEY, ' '),
    KEY_CAPITAL(KeyType.KEY),
    KEY_LEFT(KeyType.KEY),
    KEY_UP(KeyType.KEY),
    KEY_RIGHT(KeyType.KEY),
    KEY_DOWN(KeyType.KEY),
    KEY_NUMLOCK(KeyType.KEY),
    KEY_SCROLL(KeyType.KEY),
    KEY_SUBTRACT(KeyType.KEY, '-'),
    KEY_ADD(KeyType.KEY, '+'),
    KEY_DIVIDE(KeyType.KEY, '/'),
    KEY_DECIMAL(KeyType.KEY, '.'),
    KEY_NUMPAD0(KeyType.KEY, '0'),
    KEY_NUMPAD1(KeyType.KEY, '1'),
    KEY_NUMPAD2(KeyType.KEY, '2'),
    KEY_NUMPAD3(KeyType.KEY, '3'),
    KEY_NUMPAD4(KeyType.KEY, '4'),
    KEY_NUMPAD5(KeyType.KEY, '5'),
    KEY_NUMPAD6(KeyType.KEY, '6'),
    KEY_NUMPAD7(KeyType.KEY, '7'),
    KEY_NUMPAD8(KeyType.KEY, '8'),
    KEY_NUMPAD9(KeyType.KEY, '9'),
    KEY_A(KeyType.KEY, 'a'),
    KEY_B(KeyType.KEY, 'b'),
    KEY_C(KeyType.KEY, 'c'),
    KEY_D(KeyType.KEY, 'd'),
    KEY_E(KeyType.KEY, 'e'),
    KEY_F(KeyType.KEY, 'f'),
    KEY_G(KeyType.KEY, 'g'),
    KEY_H(KeyType.KEY, 'h'),
    KEY_I(KeyType.KEY, 'i'),
    KEY_J(KeyType.KEY, 'j'),
    KEY_K(KeyType.KEY, 'k'),
    KEY_L(KeyType.KEY, 'l'),
    KEY_M(KeyType.KEY, 'm'),
    KEY_N(KeyType.KEY, 'n'),
    KEY_O(KeyType.KEY, 'o'),
    KEY_P(KeyType.KEY, 'p'),
    KEY_Q(KeyType.KEY, 'q'),
    KEY_R(KeyType.KEY, 'r'),
    KEY_S(KeyType.KEY, 's'),
    KEY_T(KeyType.KEY, 't'),
    KEY_U(KeyType.KEY, 'u'),
    KEY_V(KeyType.KEY, 'v'),
    KEY_W(KeyType.KEY, 'w'),
    KEY_X(KeyType.KEY, 'x'),
    KEY_Y(KeyType.KEY, 'y'),
    KEY_Z(KeyType.KEY, 'z'),
    KEY_0(KeyType.KEY, '0'),
    KEY_1(KeyType.KEY, '1'),
    KEY_2(KeyType.KEY, '2'),
    KEY_3(KeyType.KEY, '3'),
    KEY_4(KeyType.KEY, '4'),
    KEY_5(KeyType.KEY, '5'),
    KEY_6(KeyType.KEY, '6'),
    KEY_7(KeyType.KEY, '7'),
    KEY_8(KeyType.KEY, '8'),
    KEY_9(KeyType.KEY, '9'),
    KEY_F1(KeyType.KEY),
    KEY_F2(KeyType.KEY),
    KEY_F3(KeyType.KEY),
    KEY_F4(KeyType.KEY),
    KEY_F5(KeyType.KEY),
    KEY_F6(KeyType.KEY),
    KEY_F7(KeyType.KEY),
    KEY_F8(KeyType.KEY),
    KEY_F9(KeyType.KEY),
    KEY_F10(KeyType.KEY),
    KEY_F11(KeyType.KEY),
    KEY_F12(KeyType.KEY),
    KEY_F13(KeyType.KEY),
    KEY_F14(KeyType.KEY),
    KEY_F15(KeyType.KEY),
    KEY_F16(KeyType.KEY),
    KEY_F17(KeyType.KEY),
    KEY_F18(KeyType.KEY),
    KEY_F19(KeyType.KEY),
    KEY_DELETE(KeyType.KEY),
    KEY_HOME(KeyType.KEY),
    KEY_END(KeyType.KEY);
    
}